name: Fitness
description: "A fitness app with some gym exercises."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path: ^1.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_charts: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - images/burpees_in_room.png
    - images/abdominal_supra_solo.png
    - images/biceps.png
    - images/cadeira_abdutora.png
    - images/cadeira_extensora.png
    - images/cadeira_flexora.png
    - images/crucifixo.png
    - images/desenvolvimento.png
    - images/elevacao_lateral.png
    - images/esteira.png
    - images/esteira2.png
    - images/leg45.png
    - images/leg_horizontal.png
    - images/mesa_flexora.png
    - images/panturrilha_sentado.png
    - images/puxada_articulada.png
    - images/remada_articulada_supinada.png
    - images/supino_vertical.png
    - COPYING